server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: eshop-backend-api
          uri: lb://ESHOP-BACKEND-API
          predicates:
            - Path=/api/v1/**
        - id: eshop-admin
          uri: lb://ESHOP-ADMIN
          predicates:
            - Path=/admin/**
        - id: eshop-picture-service-api
          uri: lb://ESHOP-PICTURE-SERVICE-API
          predicates:
          - Path=/api/**
